import Head from "next/head";
import Image from "next/image";
import React from "react";
import MapBox from "../components/MapBox";
import dummyParkingLots from "../dummies/parkingLots";
import initializeNotification from "../utils/fcm";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MapBox parkingLots={dummyParkingLots} />

      {/* <button
          onClick={() => {
            navigator.serviceWorker.register("/service-worker.js").then(
              async (registration) => {
                const token = await initializeNotification(registration);
                await navigator.clipboard.writeText(token);
                alert("Your token was copied");
              },
              (err) => console.error(err)
            );
          }}
        >
          request notification
        </button> */}
    </div>
  );
}
